name: Get package metadata
description: Get the metadata for a given package based on the package.json file
runs:
  using: node24
  main: dist/index.js

inputs:
  package-json-path:
    description: "The path to the package.json file"
    type: string
    required: false
    default: ./package.json

outputs:
  package-name:
    description: "The name of the package"
  package-version:
    description: "The version number"
