name: Commit a version change (Internal)
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-major-version:
    permissions:
      contents: write
      pull-requests: write
    uses: $/.github/workflows/commit-version-change.yml
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: major
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

  check-minor-version:
    permissions:
      contents: write
      pull-requests: write
    uses: $/.github/workflows/commit-version-change.yml
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: minor
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

  check-patch-version:
    permissions:
      contents: write
      pull-requests: write
    uses: $/.github/workflows/commit-version-change.yml
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      version-type: patch
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
