name: Create GitHub Release (Internal)
on:
  push:
    branches: ["main"]

jobs:
  create-github-release:
    permissions:
      contents: write
    uses: $/.github/workflows/create-github-release.yml
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
