name: Restrict alex-up-bot branches (Internal)

on:
  pull_request:
    branches: ["main"]

jobs:
  restrict-alex-up-bot-branches:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: $/.github/workflows/restrict-alex-up-bot-branches.yml
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
