name: Update Dependencies (Internal)
on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 5

jobs:
  update-dependencies:
    permissions:
      contents: write
      pull-requests: write
    uses: $/.github/workflows/update-dependencies.yml
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
    with:
      CLIENT_ID: ${{ vars.ALEX_UP_BOT_CLIENT_ID }}
      update_pnpm: true
      update_javascript_dependencies: true
      update_actions: true
      update_python_dependencies: true
