name: Create pull request templates

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
    inputs:
      run-build:
        type: boolean
        default: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request-templates:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup GitHub user
        run: |
          git config --global user.name "alex-up-bot"
          git config --global user.email "alexupbot@bot.com"

      - name: Use PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install alex-c-line
        uses: alextheman231/typescript-actions/actions/safe-npm-dependency-global-install@52cf8adbb2d435944bbd882e03d0be6cdaeac243 # v1.2.1
        with:
          package-name: alex-c-line
          dependency-group: devDependencies
          strict-version-resolution: false

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        if: ${{ inputs.run-build }}
        run: pnpm run build

      - name: Create pull request templates
        run: alex-c-line template pull-request create

      - name: Get alex-up-bot GitHub token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: alex-up-bot <alexupbot@bot.com>
          committer: alex-up-bot <alexupbot@bot.com>
          branch: alex-up-bot/update-pull-request-templates
          base: main
          commit-message: Update pull request templates
          title: "Update pull request templates"
          body-path: .github/PULL_REQUEST_TEMPLATE/documentation_change.md
