name: Create feature docs

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup GitHub user
        run: |
          git config --global user.name "alex-up-bot"
          git config --global user.email "alexupbot@bot.com"

      - name: Use PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build the package
        run: pnpm run build

      - name: Create feature docs
        run: pnpm run create-feature-docs

      - name: Get alex-up-bot GitHub token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: alex-up-bot <alexupbot@bot.com>
          committer: alex-up-bot <alexupbot@bot.com>
          branch: alex-up-bot/create-feature-docs
          base: main
          commit-message: Create feature docs
          title: "Create feature docs"
          body-path: .github/PULL_REQUEST_TEMPLATE/documentation_change.md
