name: End-to-end Node Package CI

on:
  workflow_call:
    inputs:
      os:
        description: "The operating systems to run the workflow on"
        required: false
        default: '["ubuntu-latest", "macos-latest"]'
        type: string
      node-version:
        description: The Node version to use
        type: string
        required: false
        default: "22"

permissions:
  contents: read

jobs:
  end-to-end-ci-steps:
    if: ${{ github.head_ref != 'alex-up-bot/change-major-version' && github.head_ref != 'alex-up-bot/change-minor-version' && github.head_ref != 'alex-up-bot/change-patch-version' }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run end-to-end tests
        run: pnpm run test-end-to-end

  end-to-end-ci:
    needs: end-to-end-ci-steps
    runs-on: ubuntu-latest
    if: always()
    env:
      CI_STATUS: ${{ needs.end-to-end-ci-steps.result }}
    steps:
      - name: Report on any matrix failures
        run: |
          if [ "$CI_STATUS" == "failure" ] || [ "$CI_STATUS" == "cancelled" ]; then
            exit 1
          fi
