name: PNPM CI

on:
  workflow_call:
    inputs:
      use_playwright:
        description: "Install the necessary system dependencies for Playwright"
        required: false
        default: false
        type: boolean
      os:
        description: "The operating systems to run the workflow on"
        required: false
        default: '["ubuntu-latest"]' # Lol this is stupid!
        type: string

permissions:
  contents: read

jobs:
  source-code-ci-steps:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }} # VERY stupid!
    if: ${{ github.head_ref != 'alex-up-bot/change-major-version' && github.head_ref != 'alex-up-bot/change-minor-version' && github.head_ref != 'alex-up-bot/change-patch-version' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Cache Playwright browsers
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: ${{ inputs.use_playwright == true }}
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml', 'playwright.config.ts') }}
          restore-keys: ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        if: ${{ inputs.use_playwright == true }}
        run: pnpm exec playwright install --with-deps

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Run linting checks
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

  source-code-ci:
    needs: source-code-ci-steps
    runs-on: ubuntu-latest
    if: always()
    env:
      CI_STATUS: ${{ needs.source-code-ci-steps.result }}
    steps:
      - name: Report on any matrix failures
        run: |
          if [ "$CI_STATUS" == "failure" ] || [ "$CI_STATUS" == "cancelled" ]; then
            exit 1
          fi

  version-change-ci:
    uses: ./.github/workflows/version-change-ci.yml
