name: Check version tag
on:
  workflow_call:
    secrets:
      APP_PRIVATE_KEY:
        required: true
    inputs:
      CLIENT_ID:
        type: string
        required: true
      node-version:
        description: The Node version to use
        type: string
        required: false
        default: "22"
    outputs:
      tag-exists:
        description: "True if the GitHub Release occurred"
        value: ${{ jobs.check-tag.outputs.tag-exists }}
      tag:
        description: "The tag that was checked based on package.json"
        value: ${{ jobs.check-tag.outputs.tag }}

jobs:
  check-tag:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      tag-exists: ${{ steps.check-tag.outputs.tag_exists }}
      tag: ${{ steps.check-tag.outputs.tag_exists == 'true' && steps.get-package-data.outputs.version || '' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Fetch tags from main
        run: git fetch --tags origin

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node-version }}

      - name: Get package data from package.json
        id: get-package-data
        uses: $/composite/get-package-metadata

      - name: Check if version tag exists
        id: check-tag
        env:
          VERSION: ${{ steps.get-package-data.outputs.package-version }}
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/$VERSION$"; then
            echo "Version tag $VERSION exists."
            echo "tag_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "Version tag for $VERSION does not exist."
            echo "tag_exists=false" >> "$GITHUB_OUTPUT"
          fi
