name: Scheduled Patch Release

on:
  workflow_call:
    inputs:
      node-version:
        description: The Node version to use
        type: string
        required: false
        default: "22"
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

jobs:
  scheduled-patch-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      HUSKY: 0
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install alex-c-line
        uses: alextheman231/typescript-actions/actions/safe-npm-dependency-global-install@d068a38becb783c3a1a3a63593055abad8811593 # v1.3.6
        with:
          package-name: alex-c-line
          dependency-group: devDependencies
          strict-version-resolution: false

      - name: Fetch tags
        run: |
          git fetch --unshallow origin main
          git fetch --tags origin

      - name: Get commits from previous tag to now
        id: get_commits
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0)
          COMMITS=$(git log "$PREVIOUS_TAG"..HEAD --pretty=format:"   - %s")
          {
            echo "commits<<EOF"
            echo "$COMMITS"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create the release note
        env:
          COMMITS: ${{ steps.get_commits.outputs.commits }}
        run: |
          CONTENT=$(printf "%s\n%s" "- Automated release" "$COMMITS")
          alex-c-line template release-note create patch --content "$CONTENT"

      - name: Get next version
        id: get_next_version
        run: |
          NEXT_VERSION=$(npm version patch --no-git-tag-version)
          echo "version=$NEXT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Find release note
        id: get_release_note_path
        env:
          NEXT_VERSION: ${{ steps.get_next_version.outputs.version }}
        run: |
          RELEASE_NOTE_PATH=$(alex-c-line template release-note path "$NEXT_VERSION")
          echo "path=$RELEASE_NOTE_PATH" >> "$GITHUB_OUTPUT"

      - name: Change the status in the release note to 'Released'
        env:
          RELEASE_NOTE_PATH: ${{ steps.get_release_note_path.outputs.path }}
        run: alex-c-line template release-note set-status "$RELEASE_NOTE_PATH" Released

      - name: Format the release note
        run: pnpm run format-markdownlint

      - name: Get alex-up-bot GitHub token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_ID}}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Create Pull Request
        id: pull-request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: alex-up-bot <alexupbot@bot.com>
          committer: alex-up-bot <alexupbot@bot.com>
          branch: alex-up-bot/auto-release
          base: main
          title: "Change version number to ${{ steps.get_next_version.outputs.version }}"
          commit-message: "Change version number to ${{ steps.get_next_version.outputs.version }}"
          body-path: ${{ steps.get_release_note_path.outputs.path }}

      - name: Label the pull request as low risk, documentation, and tooling
        env:
          PULL_REQUEST_URL: ${{ steps.pull-request.outputs.pull-request-url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
        run: gh pr edit $PULL_REQUEST_URL --add-label "low risk,tooling,documentation"
