name: Update Dependencies
on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
    inputs:
      update_pnpm:
        description: "Update the PNPM package manager itself"
        required: false
        default: false
        type: boolean
      update_javascript_dependencies:
        description: "Update the direct JavaScript dependencies"
        required: false
        default: false
        type: boolean
      update_actions:
        description: "Update the GitHub Actions"
        required: false
        default: false
        type: boolean
      update_python_dependencies:
        description: "Update Python dependencies with PDM"
        required: false
        default: false
        type: boolean
      update_terraform:
        description: "Update Terraform"
        required: false
        default: false
        type: boolean
      runs-on:
        description: "The Operating System to use"
        required: false
        default: "ubuntu-latest"
        type: string

jobs:
  update-dependencies:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: write
      pull-requests: write
    env:
      HUSKY: 0

    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use PNPM
        if: ${{ inputs.update_javascript_dependencies == true || inputs.update_pnpm == true || inputs.update_actions == true }}
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - name: Use Node.js
        if: ${{ inputs.update_javascript_dependencies == true || inputs.update_pnpm == true || inputs.update_actions == true }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Enable Corepack
        if: ${{ inputs.update_pnpm == true }}
        run: |
          corepack enable
          corepack --version

      - name: Get alex-up-bot GitHub token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup GitHub user
        run: |
          git config --global user.name "alex-up-bot"
          git config --global user.email "alexupbot@bot.com"

      - name: Install dependencies
        if: ${{ inputs.update_javascript_dependencies == true || inputs.update_pnpm == true }}
        run: pnpm install

      - name: Install actions-up
        if: ${{ inputs.update_actions == true }}
        uses: alextheman231/typescript-actions/actions/safe-npm-dependency-global-install@53b2250b94cc23013b99e05c29ba72a98a4a7280 # v1.2.0
        with:
          package-name: actions-up
          package-manager: pnpm
          dependency-group: devDependencies
          strict-version-resolution: false

      - name: Update PNPM
        if: ${{ inputs.update_pnpm == true }}
        run: corepack use pnpm@latest

      - name: Commit PNPM update
        if: ${{ inputs.update_pnpm == true }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@ec0a721b5d0c0f9fd8b86437636f9bcbc64218ef # v11.0.1
        with:
          message: "Update PNPM"

      - name: Update JavaScript dependencies
        if: ${{ inputs.update_javascript_dependencies }}
        run: |
          pnpm run update-dependencies
          pnpm install --no-frozen-lockfile

      - name: Commit JavaScript dependencies updates
        if: ${{ inputs.update_javascript_dependencies }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@ec0a721b5d0c0f9fd8b86437636f9bcbc64218ef # v11.0.1
        with:
          message: "Update JavaScript dependencies"

      - name: Update GitHub Actions
        if: ${{ inputs.update_actions == true }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: actions-up -y

      - name: Commit GitHub Actions updates
        if: ${{ inputs.update_actions == true }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@ec0a721b5d0c0f9fd8b86437636f9bcbc64218ef # v11.0.1
        id: commit_actions_updates
        with:
          message: "Update GitHub Actions"

      - name: Setup PDM
        if: ${{ inputs.update_python_dependencies == true }}
        run: pip install pdm

      - name: Install Python dependencies
        if: ${{ inputs.update_python_dependencies == true }}
        run: pdm install

      - name: Update Python dependencies
        if: ${{ inputs.update_python_dependencies == true }}
        run: pdm update --unconstrained --save-exact

      - name: Format the pyproject.toml file
        run: pdm run format-pyproject
        continue-on-error: true

      - name: Commit Python updates
        if: ${{ inputs.update_python_dependencies == true }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@ec0a721b5d0c0f9fd8b86437636f9bcbc64218ef # v11.0.1
        with:
          message: "Update Python dependencies"

      - name: Setup Terraform
        if: ${{ inputs.update_terraform == true }}
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.14.3

      - name: Update Terraform Providers
        if: ${{ inputs.update_terraform == true }}
        run: terraform init -upgrade -backend=false

      - name: Commit Terraform updates
        if: ${{ inputs.update_terraform == true }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@ec0a721b5d0c0f9fd8b86437636f9bcbc64218ef # v11.0.1
        id: commit_terraform_updates
        with:
          message: "Update Terraform Providers"

      - name: Create Pull Request
        id: pull-request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: alex-up-bot <alexupbot@bot.com>
          committer: alex-up-bot <alexupbot@bot.com>
          branch: alex-up-bot/update-dependencies
          base: main
          title: "Update dependencies"
          body-path: .github/PULL_REQUEST_TEMPLATE/tooling_change.md
