name: Update Dependencies
on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
    inputs:
      update_pnpm:
        description: "Update the PNPM package manager itself"
        required: false
        default: false
        type: boolean
      update_javascript_dependencies:
        description: "Update the direct JavaScript dependencies"
        required: false
        default: false
        type: boolean
      update_actions:
        description: "Update the GitHub Actions"
        required: false
        default: false
        type: boolean
      update_python_dependencies:
        description: "Update Python dependencies with PDM"
        required: false
        default: false
        type: boolean
      update_terraform:
        description: "Update Terraform"
        required: false
        default: false
        type: boolean
      runs-on:
        description: "The Operating System to use"
        required: false
        default: "ubuntu-latest"
        type: string

jobs:
  update-dependencies:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: write
      pull-requests: write
    env:
      HUSKY: 0

    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use PNPM
        if: ${{ inputs.update_javascript_dependencies == true || inputs.update_pnpm == true || inputs.update_actions == true }}
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          run_install: false

      - name: Use Node.js
        if: ${{ inputs.update_javascript_dependencies == true || inputs.update_pnpm == true || inputs.update_actions == true }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Enable Corepack
        if: ${{ inputs.update_pnpm == true }}
        run: |
          corepack enable
          corepack --version

      - name: Get alex-up-bot GitHub token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-actions: write
          permission-workflows: write

      - name: Setup GitHub user
        run: |
          git config --global user.name "alex-up-bot"
          git config --global user.email "alexupbot@bot.com"

      - name: Install dependencies
        if: ${{ inputs.update_javascript_dependencies == true || inputs.update_pnpm == true }}
        run: pnpm install

      - name: Install actions-up
        if: ${{ inputs.update_actions == true }}
        uses: alextheman231/typescript-actions/actions/safe-npm-dependency-global-install@52cf8adbb2d435944bbd882e03d0be6cdaeac243 # v1.2.1
        with:
          package-name: actions-up
          package-manager: npm
          dependency-group: devDependencies
          strict-version-resolution: false

      - name: Update PNPM
        if: ${{ inputs.update_pnpm == true }}
        run: corepack use pnpm@latest

      - name: Commit PNPM update
        if: ${{ inputs.update_pnpm == true }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@b392a15552197a9ee42f5927ecf5b61852152c72 # v11.2.5
        with:
          message: "Update PNPM"

      - name: Update JavaScript dependencies
        if: ${{ inputs.update_javascript_dependencies }}
        run: |
          pnpm run update-dependencies
          pnpm install --no-frozen-lockfile

      - name: Commit JavaScript dependencies updates
        if: ${{ inputs.update_javascript_dependencies }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@b392a15552197a9ee42f5927ecf5b61852152c72 # v11.2.5
        with:
          message: "Update JavaScript dependencies"

      - name: Update GitHub Actions
        if: ${{ inputs.update_actions == true }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: actions-up -y

      - name: Commit GitHub Actions updates
        if: ${{ inputs.update_actions == true }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@b392a15552197a9ee42f5927ecf5b61852152c72 # v11.2.5
        id: commit_actions_updates
        with:
          message: "Update GitHub Actions"

      - name: Setup PDM
        if: ${{ inputs.update_python_dependencies == true }}
        run: pip install pdm

      - name: Install Python dependencies
        if: ${{ inputs.update_python_dependencies == true }}
        run: pdm install

      - name: Update Python dependencies
        if: ${{ inputs.update_python_dependencies == true }}
        run: |
          pdm update --unconstrained --save-exact
          pdm install

      - name: Format the pyproject.toml file
        run: pdm run format-pyproject
        if: ${{ inputs.update_python_dependencies == true }}
        continue-on-error: true

      - name: Commit Python updates
        if: ${{ inputs.update_python_dependencies == true }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@b392a15552197a9ee42f5927ecf5b61852152c72 # v11.2.5
        with:
          message: "Update Python dependencies"

      - name: Setup Terraform
        if: ${{ inputs.update_terraform == true }}
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.14.3

      - name: Update Terraform Providers
        if: ${{ inputs.update_terraform == true }}
        run: terraform init -upgrade -backend=false

      - name: Commit Terraform updates
        if: ${{ inputs.update_terraform == true }}
        uses: alextheman231/github-actions/.github/actions/commit-changes@b392a15552197a9ee42f5927ecf5b61852152c72 # v11.2.5
        id: commit_terraform_updates
        with:
          message: "Update Terraform Providers"

      - name: Create Pull Request
        id: pull-request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: alex-up-bot <alexupbot@bot.com>
          committer: alex-up-bot <alexupbot@bot.com>
          branch: alex-up-bot/update-dependencies
          base: main
          title: "Update dependencies"
          body-path: .github/PULL_REQUEST_TEMPLATE/tooling_change.md
